//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 09:39:10 PM IST 
//


package com.vodafone.xml.point;

import com.vodafone.domain.PointTwoD;

import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "point2D"
})
@XmlRootElement(name = "NearestNeighborResponse")
public class NearestNeighborResponse {

    @XmlElement(name = "Point2D", required = true)
    protected PointTwoD point2D;

    /**
     * Gets the value of the student property.
     *
     * @return
     *     possible object is
     *     {@link PointTwoD }
     *
     */
    public PointTwoD getPoint2D() {
        return point2D;
    }

    /**
     * Sets the value of the student property.
     *
     * @param point2D
     *     allowed object is
     *     {@link PointTwoD }
     *
     */
    public void setPoint2D(PointTwoD point2D) {
        this.point2D = point2D;
    }

}

