//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.30 at 08:51:31 PM EET 
//


package vodafone.xml.point;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PointTwoD" type="{http://vodafone/xml/point}PointTwoD"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pointTwoD"
})
@XmlRootElement(name = "NearestNeighborResponse")
public class NearestNeighborResponse {

    @XmlElement(name = "PointTwoD", required = true)
    protected PointTwoD pointTwoD;

    /**
     * Gets the value of the pointTwoD property.
     * 
     * @return
     *     possible object is
     *     {@link PointTwoD }
     *     
     */
    public PointTwoD getPointTwoD() {
        return pointTwoD;
    }

    /**
     * Sets the value of the pointTwoD property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointTwoD }
     *     
     */
    public void setPointTwoD(PointTwoD value) {
        this.pointTwoD = value;
    }

}
