//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.30 at 08:51:31 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vodafone/xml/point", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package vodafone.xml.point;
